import type { ExternalCatalogItem } from "../services/externalCatalog.service.js";

export const DEMO_CATALOG: ExternalCatalogItem[] = [
  {
    externalId: "tmdb-693134",
    externalSource: "DEMO",
    title: "Duna: Parte 2",
    description: "Paul Atreides se une a Chani e aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família.",
    type: "MOVIE",
    category: "Ficção Científica / Ação",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    suggestedPrice: 45.0,
  },
  {
    externalId: "tmdb-550",
    externalSource: "DEMO",
    title: "Clube da Luta",
    description: "Um homem desiludido cria um clube secreto de combate com um vendedor de sabão misterioso.",
    type: "MOVIE",
    category: "Drama / Suspense",
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80",
    suggestedPrice: 35.0,
  },
  {
    externalId: "tm-coldplay-2026",
    externalSource: "DEMO",
    title: "Coldplay - Music of the Spheres World Tour",
    description: "Turnê mundial sustentável do Coldplay trazendo os maiores sucessos da banda com show de luzes e pulseiras reluzentes.",
    type: "SHOW",
    category: "Rock / Pop",
    imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80",
    suggestedPrice: 350.0,
  },
  {
    externalId: "tm-taylor-2026",
    externalSource: "DEMO",
    title: "Taylor Swift - The Eras Tour",
    description: "Uma celebração da jornada musical de Taylor Swift abrangendo todas as suas eras em uma apresentação épica de 3 horas.",
    type: "SHOW",
    category: "Pop",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
    suggestedPrice: 480.0,
  },
  {
    externalId: "tm-rock-in-rio",
    externalSource: "DEMO",
    title: "Festival Rock in Rio - Palco Mundo",
    description: "O maior festival de música e entretenimento do mundo com atrações nacionais e internacionais.",
    type: "SHOW",
    category: "Festival / Rock",
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=800&q=80",
    suggestedPrice: 520.0,
  },
];
