import type { ExternalCatalogItem } from "../services/externalCatalog.service.js";

export const DEMO_CATALOG: ExternalCatalogItem[] = [
  // --- SHOWS ---
  {
    externalId: "tm-metallica-m72",
    externalSource: "DEMO",
    title: "Metallica - M72 World Tour",
    description: "A lendária banda de Heavy Metal traz a turnê mundial M72 com palco circular inovador no centro do estádio.",
    type: "SHOW",
    category: "Heavy Metal / Rock",
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1200&q=80",
    suggestedPrice: 420.0,
  },
  {
    externalId: "tm-coldplay-2026",
    externalSource: "DEMO",
    title: "Coldplay - Music of the Spheres World Tour",
    description: "Turnê mundial sustentável do Coldplay trazendo os maiores sucessos da banda com show de luzes e pulseiras reluzentes.",
    type: "SHOW",
    category: "Rock / Pop",
    imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80",
    suggestedPrice: 350.0,
  },
  {
    externalId: "tm-taylor-2026",
    externalSource: "DEMO",
    title: "Taylor Swift - The Eras Tour",
    description: "Uma celebração da jornada musical de Taylor Swift abrangendo todas as suas eras em uma apresentação épica de 3 horas.",
    type: "SHOW",
    category: "Pop",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    suggestedPrice: 480.0,
  },
  {
    externalId: "tm-rock-in-rio",
    externalSource: "DEMO",
    title: "Festival Rock in Rio - Palco Mundo",
    description: "O maior festival de música e entretenimento do mundo com atrações nacionais e internacionais.",
    type: "SHOW",
    category: "Festival / Rock",
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1200&q=80",
    suggestedPrice: 520.0,
  },
  {
    externalId: "tm-alok-ocean",
    externalSource: "DEMO",
    title: "Alok - The Ocean Electronic Experience",
    description: "Show imersivo com efeitos visuais em laser 3D e pirotecnia de ponta ao som das melhores tracks eletrônicas.",
    type: "SHOW",
    category: "Eletrônica / EDM",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    suggestedPrice: 220.0,
  },

  // --- FILMES ---
  {
    externalId: "tmdb-693134",
    externalSource: "DEMO",
    title: "Duna: Parte 2",
    description: "Paul Atreides se une a Chani e aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família.",
    type: "MOVIE",
    category: "Ficção Científica / Ação",
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80",
    suggestedPrice: 65.0,
  },
  {
    externalId: "tmdb-155",
    externalSource: "DEMO",
    title: "Batman: O Cavaleiro das Trevas",
    description: "Batman enfrenta o Coringa em Gotham City em um confronto psicológico épico sobre justiça e anarquia.",
    type: "MOVIE",
    category: "Ação / Policial",
    imageUrl: "https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=1200&q=80",
    suggestedPrice: 55.0,
  },
  {
    externalId: "tmdb-157336",
    externalSource: "DEMO",
    title: "Interestelar",
    description: "Uma equipe de exploradores viaja através de um buraco de minhoca no espaço para garantir a sobrevivência da humanidade.",
    type: "MOVIE",
    category: "Sci-Fi / Drama",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    suggestedPrice: 48.0,
  },
  {
    externalId: "tmdb-1022789",
    externalSource: "DEMO",
    title: "Divertida Mente 2",
    description: "Riley entra na adolescência e sua mente passa por uma grande reforma para dar lugar a novas emoções inesperadas.",
    type: "MOVIE",
    category: "Animação / Família",
    imageUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1200&q=80",
    suggestedPrice: 42.0,
  },
];
